services:
  node_app:
    build: .
    container_name: node_server
    restart: unless-stopped
    networks:
      - nginx_default
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "0.5"  # Limits the container to 50% of a single CPU core
          memory: "512M"  # Limits memory usage to 512MB

networks:
  nginx_default:
    external: true
