services:
  node_app:
    image: valedobrandi/node_app
    networks:
      - default-network
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
    secrets:
      - postgres_user_secret
      - postgres_password_secret
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

secrets:
  postgres_user_secret:
    external: true
  postgres_password_secret:
    external: true

networks:
  default-network:
    external: true